version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test jacocoTestReport
      - store_artifacts:
          path: ~/repo/build/jacocoHtml
      - setup_remote_docker
      - run:
          name: Build prerequisites
          command: |
            docker --version
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            sudo apt-get install make
      - run:
          name: Build service
          command: make build

      - deploy:
          command: |
            make build -B;
            make install tag-develop;